//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessagesResource_ptBR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessagesResource_ptBR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reservatio.Resources.ExceptionMessagesResource.ptBR", typeof(ExceptionMessagesResource_ptBR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As entidades informadas não devem ser nulas..
        /// </summary>
        public static string Informed_entities_must_not_be_null_ {
            get {
                return ResourceManager.GetString("Informed entities must not be null.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado nenhum registro com o identificador informado..
        /// </summary>
        public static string No_record_was_found_with_the_given_identifier_ {
            get {
                return ResourceManager.GetString("No record was found with the given identifier.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A entidade informada não deve ser nula..
        /// </summary>
        public static string The_informed_entity_must_not_be_null_ {
            get {
                return ResourceManager.GetString("The informed entity must not be null.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar um filtro de busca não nulo..
        /// </summary>
        public static string You_must_enter_a_non_null_search_filter_ {
            get {
                return ResourceManager.GetString("You must enter a non-null search filter.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar um identificador não nulo positivo..
        /// </summary>
        public static string You_must_enter_a_positive_non_null_identifier_ {
            get {
                return ResourceManager.GetString("You must enter a positive non-null identifier.", resourceCulture);
            }
        }
    }
}
