//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessagesResource_ptBR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessagesResource_ptBR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reservatio.Resources.ValidationMessagesResource.ptBR", typeof(ValidationMessagesResource_ptBR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar uma data entre {0} e {1}.
        /// </summary>
        public static string Is_necessary_inform_a_date_between__0__and__1_ {
            get {
                return ResourceManager.GetString("Is necessary inform a date between {0} and {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar um valor para  o campo {0}..
        /// </summary>
        public static string Is_necessary_inform_a_value_for_the_field__0__ {
            get {
                return ResourceManager.GetString("Is necessary inform a value for the field {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve conter no mínimo {2} e no máximo {1} caracteres..
        /// </summary>
        public static string The_field__0__must_contain_at_least___2__and_at_most__1__characters_ {
            get {
                return ResourceManager.GetString("The field {0} must contain at least  {2} and at most {1} characters.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve conter somente letras..
        /// </summary>
        public static string The_field__0__must_contain_only_letters_ {
            get {
                return ResourceManager.GetString("The field {0} must contain only letters.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve conter somente números..
        /// </summary>
        public static string The_field__0__must_contain_only_numbers_ {
            get {
                return ResourceManager.GetString("The field {0} must contain only numbers.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP informado é inválido..
        /// </summary>
        public static string The_informed_CEP_is_invalid_ {
            get {
                return ResourceManager.GetString("The informed CEP is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF informado é inválido..
        /// </summary>
        public static string The_informed_CPF_is_invalid_ {
            get {
                return ResourceManager.GetString("The informed CPF is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data informada é inválida..
        /// </summary>
        public static string The_informed_date_is_invalid {
            get {
                return ResourceManager.GetString("The informed date is invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email informado é inválido..
        /// </summary>
        public static string The_informed_Email_is_invalid_ {
            get {
                return ResourceManager.GetString("The informed Email is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone informado é inválido..
        /// </summary>
        public static string The_informed_phone_is_invalid_ {
            get {
                return ResourceManager.GetString("The informed phone is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha e sua confirmação devem ser iguais..
        /// </summary>
        public static string The_password_and_his_confirmation_must_be_equals_ {
            get {
                return ResourceManager.GetString("The password and his confirmation must be equals.", resourceCulture);
            }
        }
    }
}
